name: shared
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0


dependencies:

  app_ui:
    path: C:/Users/sandi/OneDrive/Desktop/VSCode/Flutter/Apps/narangavellam/packages/app_ui
  env:
    path: ../env
  envied: ^1.1.1
  flutter:
    sdk: flutter
  intl: ^0.20.2
  logger: ^2.5.0
  powersync: ^1.13.1
