name: user_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
 database_client:
    path: ../database_client
 authentication_client:
  path: ../authentication_client/authentication_client  
 powersync_repository:
  path: C:/Users/sandi/OneDrive/Desktop/VSCode/Flutter/Apps/narangavellam/packages/powersync_repository
 rxdart: ^0.28.0
 shared:
  path: C:/Users/sandi/OneDrive/Desktop/VSCode/Flutter/Apps/narangavellam/packages/shared
 supabase_flutter: ^2.9.1

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
