name: narangavellam
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  animations: ^2.0.11
  api_repository:
    path: packages/api_repository
  app_ui:
    path: packages/app_ui
  authentication_client:
    path: C:/Users/sandi/OneDrive/Desktop/VSCode/Flutter/Apps/narangavellam/packages/authentication_client/authentication_client
  bloc: ^8.1.4
  cached_network_image: ^3.4.1
  database_client:
    path: packages/database_client
  env:
    path: packages/env
  envied: ^1.1.1
  equatable: ^2.0.7
  firebase_core: ^3.14.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_gen: ^5.10.0
  flutter_image_compress: ^2.4.0
  flutter_localizations:
    sdk: flutter
  form_fields:
    path: packages/form_fields
  gen_l10n_utils: ^1.7.8
  get: ^4.7.2
  get_it: ^8.0.3
  go_router: ^12.1.3
  google_sign_in: ^6.3.0
  hydrated_bloc: ^9.1.5
  image_cropper: ^9.1.0
  image_picker: ^1.1.2
  image_picker_plus:
    path: C:/Users/sandi/OneDrive/Desktop/VSCode/Flutter/Apps/narangavellam/packages/image_picker_plus
  insta_blocks:
    path: C:/Users/sandi/OneDrive/Desktop/VSCode/Flutter/Apps/narangavellam/packages/insta_blocks
  instagram_blocks_ui:
    path: C:/Users/sandi/OneDrive/Desktop/VSCode/Flutter/Apps/narangavellam/packages/instagram_blocks_ui
  intl: ^0.20.2
  json_annotation: ^4.9.0
  maths: ^0.0.2
  mocktail: ^1.0.4
  path_provider: ^2.1.5
  posts_repository:
    path: C:/Users/sandi/OneDrive/Desktop/VSCode/Flutter/Apps/narangavellam/packages/posts_repository
  powersync_repository:
    path: packages/powersync_repository
  shared:
    path: packages/shared
  shimmer: ^3.0.0
  slang: ^4.7.2
  slang_flutter: ^4.7.0
  sliver_tools: ^0.2.12
  supabase: ^2.8.0
  supabase_authentication_client:
    path: C:/Users/sandi/OneDrive/Desktop/VSCode/Flutter/Apps/narangavellam/packages/authentication_client/supabase_authentication_client
  supabase_flutter: ^2.9.1
  timeago: ^3.7.1
  token_storage:
    path: C:/Users/sandi/OneDrive/Desktop/VSCode/Flutter/Apps/narangavellam/packages/authentication_client/token_storage
  user_repository:
    path: packages/user_repository

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.5.1
  envied_generator: ^1.1.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.5
  slang_build_runner: ^4.7.0
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
