name: env
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  dotenv: ^4.2.0
  envied: ^1.1.1
  flutter:
    sdk: flutter
  googleapis_auth: ^2.0.0

dev_dependencies:
  build_runner: ^2.5.1
  envied_generator: ^1.1.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
