name: instagram_blocks_ui
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  app_ui:
    path: ../app_ui
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  powersync_repository:
    path: ../powersync_repository
  insta_blocks:
    path: C:/Users/sandi/OneDrive/Desktop/VSCode/Flutter/Apps/narangavellam/packages/insta_blocks
  shared:
    path: C:/Users/sandi/OneDrive/Desktop/VSCode/Flutter/Apps/narangavellam/packages/shared
  user_repository:
    path: C:/Users/sandi/OneDrive/Desktop/VSCode/Flutter/Apps/narangavellam/packages/user_repository
  flutter_image_compress: ^2.4.0
  shimmer: ^3.0.0
  carousel_slider: ^5.1.1
  inview_notifier_list: ^3.0.0
  octo_image: ^2.1.0
  flutter_blurhash: ^0.9.1
  cached_memory_image: ^1.5.0
  video_player: ^2.10.0
  smooth_video_progress: ^0.0.4
  flutter_animate: ^4.5.2
  sprung: ^3.0.1
  visibility_detector: ^0.4.0+2
  avatar_stack: ^3.0.0
  timeago: ^3.7.1
  url_launcher: ^6.3.1
  scrollable_positioned_list: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
