name: powersync_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
dependencies:
  env:
    path: ../env
  path: ">=1.8.3 <=1.9.1"
  path_provider: ^2.1.5
  powersync: ^1.13.1
  shared:
    path: ../shared
  supabase_flutter: ^2.9.1
